services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ${HOME}/volumes/codecake/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Thanhtam2004.
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airbnb
    ports:
      - "5432:5432"
